export const studentsData = [
  {
    id: 1,
    name: "Chioma Okafor",
    registrationNumber: "2024/001",
    gender: "Female",
    guardianName: "Mr. Okafor",
    guardianPhone: "080-xxxx-xxxx",
    attendance: {
      present: 45,
      absent: 2,
      late: 3,
      total: 50,
    },
  },
  {
    id: 2,
    name: "Ahmed Ibrahim",
    registrationNumber: "2024/002",
    gender: "Male",
    guardianName: "Mrs. Ibrahim",
    guardianPhone: "080-xxxx-xxxx",
    attendance: {
      present: 48,
      absent: 1,
      late: 1,
      total: 50,
    },
  },
  {
    id: 3,
    name: "Blessing Edet",
    registrationNumber: "2024/003",
    gender: "Female",
    guardianName: "Mrs. Edet",
    guardianPhone: "080-xxxx-xxxx",
    attendance: {
      present: 47,
      absent: 0,
      late: 3,
      total: 50,
    },
  },
  {
    id: 4,
    name: "David Adebayo",
    registrationNumber: "2024/004",
    gender: "Male",
    guardianName: "Mr. Adebayo",
    guardianPhone: "080-xxxx-xxxx",
    attendance: {
      present: 46,
      absent: 2,
      late: 2,
      total: 50,
    },
  },
  {
    id: 5,
    name: "Esther Okon",
    registrationNumber: "2024/005",
    gender: "Female",
    guardianName: "Mr. Okon",
    guardianPhone: "080-xxxx-xxxx",
    attendance: {
      present: 49,
      absent: 0,
      late: 1,
      total: 50,
    },
  },
  {
    id: 6,
    name: "Femi Ojo",
    registrationNumber: "2024/006",
    gender: "Male",
    guardianName: "Mrs. Ojo",
    guardianPhone: "080-xxxx-xxxx",
    attendance: {
      present: 44,
      absent: 3,
      late: 3,
      total: 50,
    },
  },
  {
    id: 7,
    name: "Gloria Okoye",
    registrationNumber: "2024/007",
    gender: "Female",
    guardianName: "Mr. Okoye",
    guardianPhone: "080-xxxx-xxxx",
    attendance: {
      present: 47,
      absent: 1,
      late: 2,
      total: 50,
    },
  },
  {
    id: 8,
    name: "Habeeb Lawal",
    registrationNumber: "2024/008",
    gender: "Male",
    guardianName: "Mrs. Lawal",
    guardianPhone: "080-xxxx-xxxx",
    attendance: {
      present: 48,
      absent: 0,
      late: 2,
      total: 50,
    },
  },
  {
    id: 9,
    name: "Ifeoma Nwafor",
    registrationNumber: "2024/009",
    gender: "Female",
    guardianName: "Mr. Nwafor",
    guardianPhone: "080-xxxx-xxxx",
    attendance: {
      present: 46,
      absent: 2,
      late: 2,
      total: 50,
    },
  },
  {
    id: 10,
    name: "James Okoro",
    registrationNumber: "2024/010",
    gender: "Male",
    guardianName: "Mrs. Okoro",
    guardianPhone: "080-xxxx-xxxx",
    attendance: {
      present: 49,
      absent: 0,
      late: 1,
      total: 50,
    },
  },
  {
    id: 11,
    name: "Kemi Adewale",
    registrationNumber: "2024/011",
    gender: "Female",
    guardianName: "Mr. Adewale",
    guardianPhone: "080-xxxx-xxxx",
    attendance: {
      present: 45,
      absent: 3,
      late: 2,
      total: 50,
    },
  },
  {
    id: 12,
    name: "Kunle Adebayo",
    registrationNumber: "2024/012",
    gender: "Male",
    guardianName: "Mrs. Adebayo",
    guardianPhone: "080-xxxx-xxxx",
    attendance: {
      present: 47,
      absent: 1,
      late: 2,
      total: 50,
    },
  },
  {
    id: 13,
    name: "Lola Adefemi",
    registrationNumber: "2024/013",
    gender: "Female",
    guardianName: "Mr. Adefemi",
    guardianPhone: "080-xxxx-xxxx",
    attendance: {
      present: 48,
      absent: 0,
      late: 2,
      total: 50,
    },
  },
  {
    id: 14,
    name: "Mabel Akpan",
    registrationNumber: "2024/014",
    gender: "Female",
    guardianName: "Mr. Akpan",
    guardianPhone: "080-xxxx-xxxx",
    attendance: {
      present: 46,
      absent: 2,
      late: 2,
      total: 50,
    },
  },
];
